# -*- coding: utf-8 -*-
"""covid19_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HB4rpSk12aZDKGJBllLpo4AYTYaYuwkS

# COVID-19 Data Analysis and Forecasting Project

Project Description:
This project performs COVID-19 data analysis,
visualization, and forecasting using Python libraries
like Pandas, Matplotlib, Seaborn, and Prophet.

Features:
- Data Cleaning
- Data Visualization
- Country-wise Analysis
- Time Series Forecasting

Author: Disha Kataria
"""

# Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Load Dataset
 = pd.read_csv('Covid_19_Clean_Complete.csv')

df

"""### Dataset Information"""

df.shape

df.info()

# Rename Columns
df.rename(columns = {
    "Province/State" : "State",
    "Country/Region" : "Country"
}, inplace = True)

df

# Date Analysis
df['Date'].value_counts() # On each date, how many data points are recorded.

df['Date'].max() # Last date recorded

# Country-wise Summary
df.groupby(['Country'])[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum().reset_index()

# Latest Date Records
top_date = df[df['Date'] == df['Date'].max()]

top_date.head()

top_date.groupby(['Country'])[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum().reset_index()

# Confirmed Cases Visualization
confirmed_cases = df.groupby(['Date'])['Confirmed'].sum().reset_index()
plt.figure(figsize = (20,5))
sns.lineplot(data = confirmed_cases, x = 'Date', y = 'Confirmed')
plt.xlabel('Dates')
plt.ylabel('Confirmed Cases')
plt.show()

# Death Cases Visualization
deaths_cases = df.groupby(['Date'])['Deaths'].sum().reset_index()
plt.figure(figsize = (20,10))
sns.lineplot(data = deaths_cases, x = 'Date', y = 'Deaths')
plt.xlabel('Dates')
plt.ylabel('Death Cases')
plt.show()

# Recovered Cases Visualization
recovered_cases = df.groupby(['Date'])['Recovered'].sum().reset_index()
plt.figure(figsize = (20,10))
sns.lineplot(data = recovered_cases, x = 'Date', y = 'Recovered')
plt.xlabel('Dates')
plt.ylabel('Recovered Cases')
plt.show()

# Active Cases Visualization
active_cases = df.groupby(['Date'])['Active'].sum().reset_index()
plt.figure(figsize = (20,10))
sns.lineplot(data = active_cases, x = 'Date', y = 'Active')
plt.xlabel('Dates')
plt.ylabel('Active Cases')
plt.show()

plt.figure(figsize = (40, 10))
sns.pointplot(data = confirmed_cases, x = 'Date', y = 'Confirmed', color = 'Red')
sns.pointplot(data = deaths_cases, x = 'Date', y = 'Deaths', color = 'Blue')
sns.pointplot(data = active_cases, x = 'Date', y = 'Active', color = 'Yellow')
sns.pointplot(data = recovered_cases, x = 'Date', y = 'Recovered', color = 'Green')
plt.xlabel('Dates')
plt.show()

"""## Top 3 Most Affected Countries
1. US
2. China
3. India
"""

US = df[df['Country'] == 'US']
US = US.groupby(['Date'])[['Confirmed', 'Active', 'Recovered', 'Deaths']].sum().reset_index()
US

China = df[df['Country'] == 'China']
China = China.groupby(['Date'])[['Confirmed', 'Active', 'Recovered', 'Deaths']].sum().reset_index()
China

India = df[df['Country'] == 'India']
India = India.groupby(['Date'])[['Confirmed', 'Active', 'Recovered', 'Deaths']].sum().reset_index()
India

plt.figure(figsize = (20, 10))
sns.pointplot(data = US, x = 'Date', y = 'Confirmed', color = 'Red')
sns.pointplot(data = China, x = 'Date', y = 'Confirmed', color = 'Blue')
sns.pointplot(data = India, x = 'Date', y = 'Confirmed', color = 'Yellow')

plt.ylabel('No. of Confirmed Cases')
plt.xlabel('Dates')
plt.show()

plt.figure(figsize=(20,5))
sns.pointplot(data=US,x='Date',y='Recovered',color='Red')
sns.pointplot(data=China,x='Date',y='Recovered',color='Blue')
sns.pointplot(data=India,x='Date',y='Recovered',color='Yellow')

plt.ylabel('No. of Recovered Cases')
plt.xlabel('Dates')
plt.show()

plt.figure(figsize=(20,5))
sns.pointplot(data=US,x='Date',y='Active',color='Red')
sns.pointplot(data=China,x='Date',y='Active',color='Blue')
sns.pointplot(data=India,x='Date',y='Active',color='Yellow')

plt.ylabel('No. of Active Cases')
plt.xlabel('Dates')
plt.show()

plt.figure(figsize=(20,5))
sns.pointplot(data=US,x='Date',y='Deaths',color='Red')
sns.pointplot(data=China,x='Date',y='Deaths',color='Blue')
sns.pointplot(data=India,x='Date',y='Deaths',color='Yellow')

plt.ylabel('No. of Deaths Cases')
plt.xlabel('Dates')
plt.show()

"""# Model Bulding

## Install Prophet (Run only once)
### !pip install prophet
'''
Prophet is a time series forecasting tool developed by Facebook that’s designed to be easy to use and effective for a wide range
of time series data. It’s particularly useful for data that has strong seasonal effects (like daily or weekly patterns) and includes
important dates or events that can impact the forecast.
'''
"""

# Install Prophet (Run only once)

# !pip install prophet

# Forecasting Preparation
confirmed_cases=df.groupby(['Date']).sum()['Confirmed'].reset_index()
confirmed_cases.columns = ['ds', 'y']
confirmed_cases

from prophet import Prophet

# Build Forecasting Model
model = Prophet()
model.fit(confirmed_cases)

# Future Prediction
future = model.make_future_dataframe(periods = 7)
forecasted = model.predict(future)
forecasted

forecasted[['yhat_lower','yhat','yhat_upper']]

model.plot(forecasted)
plt.show()

recovered_cases.columns = ['ds', 'y']

model_recovered = Prophet()
model_recovered.fit(recovered_cases)
future = model_recovered.make_future_dataframe(periods = 7)
forecasted = model_recovered.predict(future)
forecasted

active_cases = df.groupby(['Date'])['Active'].sum().reset_index()
active_cases.columns = ['ds', 'y']

model_active = Prophet()
model_active.fit(active_cases)

future = model_active.make_future_dataframe(periods = 7)
forecasted = model_active.predict(future)

forecasted

death_cases = df.groupby(['Date'])['Deaths'].sum().reset_index()
death_cases.columns = ['ds', 'y']

model_death = Prophet()
model_death.fit(death_cases)

future = model_death.make_future_dataframe(periods = 7)
forecasted = model_death.predict(future)

forecasted

import plotly

import plotly.express as px

world = df.groupby(['Country'])[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum().reset_index()
world

figure = px.choropleth(world, locationmode = 'country names', color='Active' ,hover_name='Country' ,range_color=[1,100000], color_continuous_scale='reds', title='World map for the Active cases')
figure.show()